//
//  Configuration.h
//  Calculator
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/08/2017
//
#ifndef Calculator_Configuration_h
#define Calculator_Configuration_h

/** The base Uri for API calls */
extern NSString* Configuration_BaseUri;

#endif
