//
//  Configuration.m
//  Calculator
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/08/2017
//
#import "Configuration.h"

/** The base Uri for API calls */
NSString* Configuration_BaseUri = @"https://examples.apimatic.io/apps/calculator";

