//
//  JSONValueTransformer+NSDate.m
//  Calculator
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/08/2017
//

#import "JSONValueTransformer+NSDate.h"
#import "NSDate+extension.h"
@implementation JSONValueTransformer (NSDate)

-(NSDate*) NSDateFromNSString:(NSString*)string
{
    return [NSDate NSDateFromNSString:string];
}

@end
