//
//  JSONValueTransformer+NSDate.h
//  Calculator
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/08/2017
//

#import "JSONValueTransformer.h"

@interface JSONValueTransformer (NSDate)

-(NSDate*) NSDateFromNSString:(NSString*)string;

@end
