//
//  OperationTypeEnum.h
//  Calculator
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/08/2017
//
#ifndef APIMATIC_OPERATIONTYPEENUM
#define APIMATIC_OPERATIONTYPEENUM
 
enum OperationTypeEnum
{
        OperationTypeSUM, //TODO: Write general description for this method
        OperationTypeSUBTRACT, //TODO: Write general description for this method
        OperationTypeMULTIPLY, //TODO: Write general description for this method
        OperationTypeDIVIDE, //TODO: Write general description for this method
};

#endif